# Looking at all years (2015 -2022) Indicators Data

In [10]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [11]:
df2015 = pd.read_csv('../indicators_clean/clean_indicators_2015.csv')
df2015['Year'] = 2015
df2015.head(3)

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Year
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0,2015
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0,2015
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0,2015

In [12]:
df2016 = pd.read_csv('../indicators_clean/clean_indicators_2016.csv')
df2016['Year'] = 2016
df2016.head(3)

,Unnamed: 0,GenHlth,Income,Sex,Stroke,PhysHlth,Diabetes,NoDocbcCost,Smoker,HvyAlcoholConsump,HeartDiseaseorAttack,MentHlth,Education,Age,AnyHealthcare,PhysActivity,DiffWalk,BMI,Year
0,0,1.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,5.0,1.0,1.0,0.0,21.0,2016
1,1,2.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,1.0,1.0,0.0,27.0,2016
2,2,3.0,7.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,5.0,13.0,1.0,1.0,0.0,20.0,2016

In [13]:
df2017 = pd.read_csv('../indicators_clean/clean_indicators_2017.csv')
df2017['Year'] = 2017
df2017.head(3)

,Unnamed: 0,GenHlth,Income,Sex,Stroke,Fruits,CholCheck,BMI,PhysHlth,HighChol,NoDocbcCost,Smoker,HvyAlcoholConsump,Education,Veggies,AnyHealthcare,Diabetes,HeartDiseaseorAttack,MentHlth,HighBP,Age,PhysActivity,DiffWalk,Veggies.1,Year
0,0,2.0,6.0,0.0,0.0,1.0,1.0,27.0,0.0,1.0,0.0,0.0,0.0,6.0,1.0,1.0,2.0,0.0,0.0,1.0,11.0,1.0,1.0,1.0,2017
1,1,2.0,8.0,1.0,0.0,1.0,1.0,29.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,1.0,0.0,0.0,0.0,1.0,10.0,1.0,0.0,1.0,2017
2,4,4.0,2.0,0.0,0.0,1.0,1.0,23.0,14.0,0.0,0.0,1.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,2017

In [14]:
df2018 = pd.read_csv('../indicators_clean/clean_indicators_2018.csv')
df2018['Year'] = 2018
df2018.head(3)

,Unnamed: 0,GenHlth,Income,Sex,Stroke,PhysHlth,Diabetes,NoDocbcCost,Smoker,HeartDiseaseorAttack,MentHlth,Education,Age,AnyHealthcare,PhysActivity,DiffWalk,HvyAlcoholConsump,BMI,Year
0,0,2.0,6.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,6.0,13.0,1.0,0.0,1.0,0.0,22.0,2018
1,1,3.0,4.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,6.0,3.0,0.0,1.0,0.0,0.0,33.0,2018
2,2,5.0,3.0,0.0,1.0,10.0,2.0,0.0,0.0,0.0,0.0,4.0,12.0,1.0,1.0,1.0,0.0,30.0,2018

In [15]:
df2019 = pd.read_csv('../indicators_clean/clean_indicators_2019.csv')
df2019['Year'] = 2019
df2019.head(3)

,Unnamed: 0,GenHlth,Income,Stroke,Fruits,HvyAlcoholConsump,BMI,CholCheck,PhysHlth,HighChol,NoDocbcCost,Smoker,Education,Veggies,AnyHealthcare,HeartDiseaseorAttack,MentHlth,HighBP,Age,Diabetes,Sex,PhysActivity,DiffWalk,Veggies.1,Year
0,0,3.0,3.0,0.0,1.0,0.0,28.0,1.0,15.0,1.0,0.0,1.0,3.0,1.0,1.0,0.0,0.0,1.0,13.0,0.0,0.0,0.0,1.0,1.0,2019
1,1,4.0,5.0,0.0,1.0,0.0,19.0,1.0,10.0,0.0,0.0,0.0,5.0,1.0,1.0,0.0,0.0,0.0,11.0,0.0,0.0,1.0,0.0,1.0,2019
2,2,3.0,7.0,0.0,1.0,0.0,32.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0,1.0,0.0,30.0,1.0,10.0,2.0,0.0,1.0,1.0,1.0,2019

In [16]:
df2020 = pd.read_csv('../indicators_clean/clean_indicators_2020.csv')
df2020['Year'] = 2020
df2020.head(3)

,Unnamed: 0,GenHlth,Income,PhysHlth,Stroke,NoDocbcCost,Smoker,HeartDiseaseorAttack,HvyAlcoholConsump,MentHlth,Education,Age,AnyHealthcare,Diabetes,Sex,PhysActivity,DiffWalk,BMI,Year
0,0,2.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,30.0,6.0,8.0,0.0,2.0,0.0,1.0,0.0,17.0,2020
1,5,4.0,5.0,20.0,0.0,0.0,1.0,0.0,0.0,30.0,4.0,10.0,1.0,2.0,1.0,1.0,0.0,27.0,2020
2,6,3.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,12.0,1.0,0.0,0.0,0.0,0.0,24.0,2020

In [17]:
df2021 = pd.read_csv('../indicators_clean/clean_indicators_2021.csv')
df2021['Year'] = 2021
df2021.head(3)

,Unnamed: 0,HighBP,GenHlth,Stroke,Fruits,HvyAlcoholConsump,BMI,Income,PhysHlth,Smoker,Education,HighChol,Veggies,CholCheck,HeartDiseaseorAttack,MentHlth,NoDocbcCost,AnyHealthcare,Age,Diabetes,Sex,PhysActivity,DiffWalk,Veggies.1,Year
0,0,0.0,5.0,0.0,1.0,0.0,15.0,5.0,20.0,1.0,4.0,1.0,1.0,1.0,0.0,10.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,1.0,2021
1,2,1.0,2.0,0.0,1.0,0.0,28.0,3.0,0.0,0.0,4.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,11.0,2.0,0.0,0.0,0.0,0.0,2021
2,3,1.0,2.0,0.0,1.0,0.0,33.0,7.0,0.0,0.0,4.0,1.0,1.0,1.0,0.0,10.0,0.0,1.0,9.0,2.0,0.0,1.0,0.0,1.0,2021

In [18]:
df2022 = pd.read_csv('../indicators_clean/clean_indicators_2022.csv')
df2022['Year'] = 2022
df2022.head(3)

,Unnamed: 0,HvyAlcoholConsump,GenHlth,Income,AnyHealthcare,Stroke,PhysHlth,NoDocbcCost,Smoker,HeartDiseaseorAttack,MentHlth,Education,Age,Diabetes,Sex,PhysActivity,DiffWalk,BMI,Year
0,1,0.0,1.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,13.0,0.0,0.0,0.0,0.0,27.0,2022
1,2,0.0,2.0,7.0,1.0,0.0,2.0,0.0,0.0,0.0,3.0,6.0,8.0,0.0,0.0,1.0,0.0,26.0,2022
2,4,0.0,4.0,5.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,1.0,0.0,22.0,2022

In [20]:
df_all = pd.concat([df2015, df2016, df2017, df2018, df2019, df2020, df2021, df2022], sort = False)
df_all.drop('Unnamed: 0', axis=1, inplace=True)
df_all

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Year,Veggies.1
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0,2015,NaN
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0,2015,NaN
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0,2015,NaN
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0,2015,NaN
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286764,0.0,NaN,NaN,NaN,24.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,1.0,4.0,7.0,0.0,0.0,0.0,2.0,6.0,4.0,2022,NaN
286765,0.0,NaN,NaN,NaN,30.0,0.0,1.0,2.0,1.0,NaN,NaN,0.0,1.0,0.0,3.0,15.0,0.0,0.0,1.0,10.0,6.0,7.0,2022,NaN
286766,0.0,NaN,NaN,NaN,31.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,3.0,6.0,7.0,2022,NaN
286767,0.0,NaN,NaN,NaN,29.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,7.0,6.0,7.0,2022,NaN
286768,1.0,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,11.0,5.0,7.0,2022,NaN

In [21]:
df_all.Year.value_counts().sort_index()

Year
2015    253680
2016    352588
2017    275854
2018    314049
2019    243317
2020    276211
2021    236378
2022    286769
Name: count, dtype: int64

In [24]:
df_all.to_csv('../indicators_clean/clean_indicators_ALL_2015_2022.csv', index=False)