# Analysis Indicators

In [1]:

import pandas as pd 
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('indicators_clean/clean_indicators_ALL_2015_2022.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Year,Veggies.1
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0,2015,NaN
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0,2015,NaN
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0,2015,NaN
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0,2015,NaN
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2238841,0.0,NaN,NaN,NaN,24.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,1.0,4.0,7.0,0.0,0.0,0.0,2.0,6.0,4.0,2022,NaN
2238842,0.0,NaN,NaN,NaN,30.0,0.0,1.0,2.0,1.0,NaN,NaN,0.0,1.0,0.0,3.0,15.0,0.0,0.0,1.0,10.0,6.0,7.0,2022,NaN
2238843,0.0,NaN,NaN,NaN,31.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,3.0,6.0,7.0,2022,NaN
2238844,0.0,NaN,NaN,NaN,29.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,7.0,6.0,7.0,2022,NaN
2238845,1.0,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,11.0,5.0,7.0,2022,NaN

In [3]:
df.HeartDiseaseorAttack.value_counts()

HeartDiseaseorAttack
0.0    2036310
1.0     202536
Name: count, dtype: int64

In [4]:
for col in df.columns:
    print(df[col].value_counts())

HeartDiseaseorAttack
0.0    2036310
1.0     202536
Name: count, dtype: int64
HighBP
0.0    581549
1.0    427680
Name: count, dtype: int64
HighChol
0.0    603343
1.0    405886
Name: count, dtype: int64
CholCheck
1.0    970378
0.0     38851
Name: count, dtype: int64
BMI
27.0     210316
26.0     174126
24.0     168644
25.0     145156
28.0     143918
          ...
96.0          5
97.0          5
99.0          4
93.0          2
100.0         1
Name: count, Length: 89, dtype: int64
Smoker
0.0    1278581
1.0     960265
Name: count, dtype: int64
Stroke
0.0    2148207
1.0      90639
Name: count, dtype: int64
Diabetes
0.0    1886578
2.0     307100
1.0      45168
Name: count, dtype: int64
PhysActivity
1.0    1713134
0.0     525712
Name: count, dtype: int64
Fruits
1.0    643208
0.0    366021
Name: count, dtype: int64
Veggies
1.0    834339
2.0    127051
0.0     47839
Name: count, dtype: int64
HvyAlcoholConsump
0.0    2093266
1.0     145580
Name: count, dtype: int64
AnyHealthcare
1.0    2104840
0.0     134006
Name: count, dtype: int64
NoDocbcCost
0.0    2040679
1.0     198167
Name: count, dtype: int64
GenHlth
2.0    780859
3.0    684720
1.0    394439
4.0    279159
5.0     99669
Name: count, dtype: int64
MentHlth
0.0     1461044
2.0      119373
30.0     118925
5.0       92041
1.0       74785
3.0       72288
10.0      67679
15.0      61065
4.0       37090
20.0      36797
7.0       34218
25.0      12820
14.0      12421
6.0       10235
8.0        7109
12.0       4925
28.0       3476
21.0       2300
29.0       1899
18.0       1244
9.0        1106
16.0       1061
27.0        839
17.0        807
22.0        695
13.0        644
11.0        486
26.0        465
24.0        463
23.0        407
19.0        139
Name: count, dtype: int64
PhysHlth
0.0     1429689
30.0     165133
2.0      128588
1.0       95758
3.0       75152
5.0       68068
10.0      49222
15.0      42630
7.0       39892
4.0       39229
20.0      27915
14.0      22504
6.0       11205
25.0      10828
8.0        7361
21.0       5245
12.0       4925
28.0       3837
29.0       1764
9.0        1687
18.0       1442
16.0       1148
27.0       1015
17.0        859
13.0        657
11.0        653
22.0        643
24.0        579
26.0        559
23.0        429
19.0        230
Name: count, dtype: int64
DiffWalk
0.0    1886730
1.0     352116
Name: count, dtype: int64
Sex
0.0    1185937
1.0    1052909
Name: count, dtype: int64
Age
10.0    261447
9.0     260955
8.0     234530
11.0    216430
7.0     200449
6.0     164804
13.0    152720
5.0     147529
12.0    145490
4.0     140026
3.0     121660
2.0      99446
1.0      93360
Name: count, dtype: int64
Education
6.0    945505
5.0    621908
4.0    551820
3.0     83536
2.0     34430
1.0      1647
Name: count, dtype: int64
Income
8.0    613464
7.0    601525
6.0    310265
5.0    233458
4.0    172523
3.0    132087
2.0     93546
1.0     81978
Name: count, dtype: int64
Year
2016    352588
2018    314049
2022    286769
2020    276211
2017    275854
2015    253680
2019    243317
2021    236378
Name: count, dtype: int64
Veggies.1
1.0    628498
0.0    127051
Name: count, dtype: int64

In [5]:
highBP_grp = df.groupby(by=['HighBP'])

In [6]:
highBP_grp.HighBP.plot(kind='bar')