# Analyzing Behavioral_Risk_Factor_Surveillance_System__BRFSS__-__National_Cardiovascular_Disease_Surveillance_Data_20240112.csv

Location: /work/shibberu/share/MA384_Data_Mining_Projects_Winter_2023-24/CDSA

Website:https://data.cdc.gov/Heart-Disease-Stroke-Prevention/Rates-and-Trends-in-Hypertension-related-Cardiovas/uc9k-vc2j/about_data

Data Description:

This dataset documents rates and trends in local hypertension-related cardiovascular disease (CVD) death rates. Specifically, this report presents county (or county equivalent) estimates of hypertension-related CVD death rates in 2000-2019 and trends during two intervals (2000-2010, 2010-2019) by age group (ages 35â€“64 years, ages 65 years and older), race/ethnicity (non-Hispanic American Indian/Alaska Native, non-Hispanic Asian/Pacific Islander, non-Hispanic Black, Hispanic, non-Hispanic White), and sex (female, male). The rates and trends were estimated using a Bayesian spatiotemporal model and a smoothed over space, time, and demographic group. Rates are age-standardized in 10-year age groups using the 2010 US population. Data source: National Vital Statistics System.

BRFFS - 
Behavioral Risk Factor Surveillance System (BRFSS) is a health-related telephone survey that is collected annually by the CDC

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 35)

In [2]:
path = "C:/Users/duvallar/OneDrive/1.RoseHulman/3.Junior/Winter/MA384/Data/Behavioral_Risk_Factor_Surveillance_System__BRFSS__-__National_Cardiovascular_Disease_Surveillance_Data_20240112.csv"

df = pd.read_csv(path)
# df.set_index('RowId', inplace=True)
df.YearStart = pd.to_datetime(df.YearStart).dt.year

df.head()

C:\Users\duvallar\AppData\Local\Temp\ipykernel_31888\3530372646.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,RowId,YearStart,LocationAbbr,LocationDesc,DataSource,PriorityArea1,PriorityArea2,PriorityArea3,PriorityArea4,Class,Topic,Question,Data_Value_Type,Data_Value_Unit,Data_Value,Data_Value_Alt,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Break_Out_Category,Break_Out,ClassId,TopicId,QuestionId,Data_Value_TypeID,BreakOutCategoryId,BreakOutId,LocationId,Geolocation
0,BRFSS~2011~01~BR001~OVR01~Age-Standardized,1970,AL,Alabama,BRFSS,NaN,NaN,NaN,NaN,Cardiovascular Diseases,Major Cardiovascular Disease,Prevalence of major cardiovascular disease amo...,Age-Standardized,Percent (%),9.9,9.9,NaN,NaN,9.2,10.7,Overall,Overall,C1,T1,BR001,AgeStdz,BOC01,OVR01,1,POINT (-86.63186076199969 32.84057112200048)
1,BRFSS~2011~01~BR001~OVR01~Crude,1970,AL,Alabama,BRFSS,NaN,NaN,NaN,NaN,Cardiovascular Diseases,Major Cardiovascular Disease,Prevalence of major cardiovascular disease amo...,Crude,Percent (%),11.0,11.0,NaN,NaN,10.2,11.9,Overall,Overall,C1,T1,BR001,Crude,BOC01,OVR01,1,POINT (-86.63186076199969 32.84057112200048)
2,BRFSS~2011~01~BR001~GEN01~Crude,1970,AL,Alabama,BRFSS,NaN,NaN,NaN,NaN,Cardiovascular Diseases,Major Cardiovascular Disease,Prevalence of major cardiovascular disease amo...,Crude,Percent (%),12.5,12.5,NaN,NaN,11.1,14.0,Gender,Male,C1,T1,BR001,Crude,BOC02,GEN01,1,POINT (-86.63186076199969 32.84057112200048)
3,BRFSS~2011~01~BR001~GEN01~Age-Standardized,1970,AL,Alabama,BRFSS,NaN,NaN,NaN,NaN,Cardiovascular Diseases,Major Cardiovascular Disease,Prevalence of major cardiovascular disease amo...,Age-Standardized,Percent (%),11.8,11.8,NaN,NaN,10.6,13.2,Gender,Male,C1,T1,BR001,AgeStdz,BOC02,GEN01,1,POINT (-86.63186076199969 32.84057112200048)
4,BRFSS~2011~01~BR001~GEN02~Age-Standardized,1970,AL,Alabama,BRFSS,NaN,NaN,NaN,NaN,Cardiovascular Diseases,Major Cardiovascular Disease,Prevalence of major cardiovascular disease amo...,Age-Standardized,Percent (%),8.3,8.3,NaN,NaN,7.5,9.1,Gender,Female,C1,T1,BR001,AgeStdz,BOC02,GEN02,1,POINT (-86.63186076199969 32.84057112200048)

In [3]:
category_columns = ['LocationAbbr', 'LocationDesc', 'DataSource', 'PriorityArea1',  'PriorityArea3', 'Class', 'Topic', 'Question', 'Data_Value_Type', 'Data_Value_Footnote', 'Break_Out_Category', 'Break_Out', 'ClassId', 'TopicId', 'QuestionId', 'Data_Value_TypeID', 'BreakOutCategoryId', 'BreakOutId', 'LocationId']

for cat in category_columns:
    df[cat] = df[cat].astype('category')

df.Geolocation = df.Geolocation.str.strip("POINT (*)")
df[['Latitude', 'Longitude']] = df['Geolocation'].str.split(" ", expand=True)
df['Latitude'] = df.Latitude.astype(str)
df['Longitude'] = df.Longitude.astype(str)


df.dtypes

RowId                           object
YearStart                        int32
LocationAbbr                  category
LocationDesc                  category
DataSource                    category
PriorityArea1                 category
PriorityArea2                  float64
PriorityArea3                 category
PriorityArea4                  float64
Class                         category
Topic                         category
Question                      category
Data_Value_Type               category
Data_Value_Unit                 object
Data_Value                     float64
Data_Value_Alt                 float64
Data_Value_Footnote_Symbol      object
Data_Value_Footnote           category
Low_Confidence_Limit           float64
High_Confidence_Limit          float64
Break_Out_Category            category
Break_Out                     category
ClassId                       category
TopicId                       category
QuestionId                    category
Data_Value_TypeID             category
BreakOutCategoryId            category
BreakOutId                    category
LocationId                    category
Geolocation                     object
Latitude                        object
Longitude                       object
dtype: object

In [4]:
df.shape

(160160, 32)

In [5]:
nan_count_per_column = df.isna().sum().sort_values(ascending=False)
print("PERCENT NaN:", '\n')
print(100* (nan_count_per_column / 160160))

PERCENT NaN:

PriorityArea4                 100.000000
PriorityArea2                 100.000000
PriorityArea1                  85.714286
High_Confidence_Limit          52.352023
Low_Confidence_Limit           52.352023
Data_Value                     51.150724
PriorityArea3                  50.000000
Data_Value_Footnote            48.849276
Data_Value_Footnote_Symbol     48.849276
Geolocation                     1.923077
BreakOutId                      0.000000
Break_Out_Category              0.000000
Data_Value_TypeID               0.000000
QuestionId                      0.000000
TopicId                         0.000000
LocationId                      0.000000
ClassId                         0.000000
Break_Out                       0.000000
Latitude                        0.000000
BreakOutCategoryId              0.000000
RowId                           0.000000
YearStart                       0.000000
Data_Value_Alt                  0.000000
Data_Value_Unit                 0.000000
Data_Value_Type                 0.000000
Question                        0.000000
Topic                           0.000000
Class                           0.000000
DataSource                      0.000000
LocationDesc                    0.000000
LocationAbbr                    0.000000
Longitude                       0.000000
dtype: float64

In [6]:
duplicate_count = df.duplicated().sum()
total_rows = len(df)
percentage_duplicates = (duplicate_count / total_rows) * 100
print("Percent Duplicates: ", percentage_duplicates.round(2), "  Duplicate Count", duplicate_count, "    Total Rows", total_rows )

Percent Duplicates:  0.0   Duplicate Count 0     Total Rows 160160

In [7]:
duplicate_df = df[df.duplicated(keep=False)].sort_values(by = ['YearStart', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'PriorityArea1', 'PriorityArea2', 'PriorityArea3', 'PriorityArea4',
       'Class', 'Topic', 'Question', 'Data_Value_Type', 'Data_Value_Unit',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit',
       'Break_Out_Category', 'Break_Out', 'ClassId', 'TopicId', 'QuestionId',
       'Data_Value_TypeID', 'BreakOutCategoryId', 'BreakOutId', 'LocationId',
       'Geolocation', 'Latitude', 'Longitude'])
duplicate_df.head(20)

Empty DataFrame
Columns: [RowId, YearStart, LocationAbbr, LocationDesc, DataSource, PriorityArea1, PriorityArea2, PriorityArea3, PriorityArea4, Class, Topic, Question, Data_Value_Type, Data_Value_Unit, Data_Value, Data_Value_Alt, Data_Value_Footnote_Symbol, Data_Value_Footnote, Low_Confidence_Limit, High_Confidence_Limit, Break_Out_Category, Break_Out, ClassId, TopicId, QuestionId, Data_Value_TypeID, BreakOutCategoryId, BreakOutId, LocationId, Geolocation, Latitude, Longitude]
Index: []

In [8]:
for col in df.columns:
    print(df[col].value_counts().sort_values())
    print()

RowId
BRFSS~2011~01~BR001~OVR01~Age-Standardized    1
BRFSS~2011~01~BR001~RAC04~Crude               1
BRFSS~2011~01~BR001~RAC04~Age-Standardized    1
BRFSS~2011~01~BR001~RAC03~Age-Standardized    1
BRFSS~2011~01~BR001~GEN01~Crude               1
                                             ..
BRFSS~2020~58~BR012~RAC02~Crude               1
BRFSS~2020~58~BR012~RAC03~Crude               1
BRFSS~2020~58~BR012~RAC03~Age-Standardized    1
BRFSS~2020~58~BR012~AGE07~Crude               1
BRFSS~2020~58~BR012~RAC07~Age-Standardized    1
Name: count, Length: 160160, dtype: int64

YearStart
1970    160160
Name: count, dtype: int64

LocationAbbr
AK     3080
IA     3080
AR     3080
AZ     3080
CA     3080
CO     3080
CT     3080
DC     3080
DE     3080
FL     3080
GA     3080
MS     3080
HI     3080
MO     3080
IL     3080
IN     3080
KS     3080
KY     3080
LA     3080
MA     3080
MD     3080
ME     3080
MI     3080
ID     3080
MT     3080
NC     3080
WV     3080
AL     3080
ND     3080
NE     3080
NH     3080
NJ     3080
NM     3080
NV     3080
NY     3080
OH     3080
OK     3080
OR     3080
PA     3080
RI     3080
SC     3080
SD     3080
TN     3080
TX     3080
USM    3080
UT     3080
VA     3080
VT     3080
WA     3080
WI     3080
MN     3080
WY     3080
Name: count, dtype: int64

LocationDesc
Alabama                 3080
Illinois                3080
Arizona                 3080
Arkansas                3080
California              3080
Colorado                3080
Connecticut             3080
Delaware                3080
Florida                 3080
Georgia                 3080
Hawaii                  3080
Missouri                3080
Idaho                   3080
Mississippi             3080
Iowa                    3080
Kansas                  3080
Kentucky                3080
Louisiana               3080
Maine                   3080
Maryland                3080
Massachusetts           3080
Median of all states    3080
Michigan                3080
Indiana                 3080
Montana                 3080
Nebraska                3080
Wisconsin               3080
Alaska                  3080
Nevada                  3080
New Hampshire           3080
New Jersey              3080
New Mexico              3080
New York                3080
North Carolina          3080
North Dakota            3080
Ohio                    3080
Oklahoma                3080
Oregon                  3080
Pennsylvania            3080
Rhode Island            3080
South Carolina          3080
South Dakota            3080
Tennessee               3080
Texas                   3080
Utah                    3080
Vermont                 3080
Virginia                3080
Washington              3080
Washington, DC          3080
West Virginia           3080
Minnesota               3080
Wyoming                 3080
Name: count, dtype: int64

DataSource
BRFSS    160160
Name: count, dtype: int64

PriorityArea1
Million Hearts    22880
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

PriorityArea3
Healthy People 2030    80080
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

Class
Cardiovascular Diseases     57200
Risk Factors               102960
Name: count, dtype: int64

Topic
Coronary Heart Disease                        11440
Diabetes                                      11440
Major Cardiovascular Disease                  11440
Nutrition                                     11440
Obesity                                       11440
Physical Inactivity                           11440
Smoking                                       11440
Stroke                                        11440
Acute Myocardial Infarction (Heart Attack)    22880
Cholesterol Abnormalities                     22880
Hypertension                                  22880
Name: count, dtype: int64

Question
Prevalence of acute myocardial infarction (heart attack) among US adults (18+); BRFSS                    11440
Prevalence of cholesterol screening in the past 5 years among US adults (20+); BRFSS                     11440
Prevalence of consuming fruits and vegetables less than 5 times per day among US adults (18+); BRFSS     11440
Prevalence of coronary heart disease among US adults (18+); BRFSS                                        11440
Prevalence of current smoking among US adults (18+); BRFSS                                               11440
Prevalence of diabetes among US adults (18+); BRFSS                                                      11440
Prevalence of high total cholesterol among US adults (20+); BRFSS                                        11440
Prevalence of hypertension among US adults (18+); BRFSS                                                  11440
Prevalence of hypertension medication use among US adults (18+) with hypertension; BRFSS                 11440
Prevalence of major cardiovascular disease among US adults (18+); BRFSS                                  11440
Prevalence of obesity among US adults (20+); BRFSS                                                       11440
Prevalence of physical inactivity among US adults (18+); BRFSS                                           11440
Prevalence of post-hospitalization rehabilitation among heart attack patients, US adults (18+); BRFSS    11440
Prevalence of stroke among US adults (18+); BRFSS                                                        11440
Name: count, dtype: int64

Data_Value_Type
Age-Standardized     58240
Crude               101920
Name: count, dtype: int64

Data_Value_Unit
Percent (%)    160160
Name: count, dtype: int64

Data_Value
99.4      1
0.1       2
99.1      4
99.3      5
48.3      6
       ...
3.7     491
3.1     491
3.3     493
2.9     502
3.0     504
Name: count, Length: 994, dtype: int64

Data_Value_Alt
 99.4        1
 0.1         2
 99.1        4
 99.3        5
 48.3        6
         ...
 3.3       493
 2.9       502
 3.0       504
-2.0     22423
-1.0     59500
Name: count, Length: 996, dtype: int64

Data_Value_Footnote_Symbol
~    22423
-    59500
Name: count, dtype: int64

Data_Value_Footnote
Statistically unstable estimates not presented [unstable by CDC standards: (standard error/estimate>0.30)]    22423
Data not available                                                                                            59500
Name: count, dtype: int64

Low_Confidence_Limit
0.1       1
99.0      1
98.9      2
98.8      3
98.4      4
       ...
2.4     541
2.5     541
2.7     545
2.6     563
2.3     570
Name: count, Length: 990, dtype: int64

High_Confidence_Limit
99.7      1
0.4       1
0.6       3
99.6      4
0.7       6
       ...
4.6     396
3.7     400
3.8     403
3.6     406
4.1     421
Name: count, Length: 993, dtype: int64

Break_Out_Category
Overall    14560
Gender     29120
Age        43680
Race       72800
Name: count, dtype: int64

Break_Out
20-24                  1560
18-24                  5720
25-44                  7280
35+                    7280
45-64                  7280
65+                    7280
75+                    7280
Female                14560
Hispanic              14560
Male                  14560
Non-Hispanic Asian    14560
Non-Hispanic Black    14560
Non-Hispanic White    14560
Other                 14560
Overall               14560
Name: count, dtype: int64

ClassId
C1     57200
C2    102960
Name: count, dtype: int64

TopicId
T1     11440
T11    11440
T12    11440
T13    11440
T14    11440
T15    11440
T4     11440
T6     11440
T10    22880
T3     22880
T9     22880
Name: count, dtype: int64

QuestionId
BR001    11440
BR002    11440
BR003    11440
BR004    11440
BR005    11440
BR011    11440
BR012    11440
BR013    11440
BR014    11440
BR016    11440
BR017    11440
BR018    11440
BR019    11440
BR020    11440
Name: count, dtype: int64

Data_Value_TypeID
AgeStdz     58240
Crude      101920
Name: count, dtype: int64

BreakOutCategoryId
BOC01    14560
BOC02    29120
BOC03    43680
BOC04    72800
Name: count, dtype: int64

BreakOutId
AGE02     1560
AGE01     5720
AGE04     7280
AGE05     7280
AGE06     7280
AGE07     7280
AGE08     7280
GEN01    14560
GEN02    14560
OVR01    14560
RAC01    14560
RAC02    14560
RAC03    14560
RAC04    14560
RAC07    14560
Name: count, dtype: int64

LocationId
1     3080
16    3080
4     3080
5     3080
6     3080
8     3080
9     3080
10    3080
11    3080
12    3080
13    3080
29    3080
15    3080
28    3080
18    3080
19    3080
20    3080
21    3080
22    3080
23    3080
24    3080
25    3080
26    3080
17    3080
30    3080
31    3080
56    3080
2     3080
32    3080
33    3080
34    3080
35    3080
36    3080
37    3080
38    3080
39    3080
40    3080
41    3080
42    3080
44    3080
45    3080
46    3080
47    3080
48    3080
49    3080
50    3080
51    3080
53    3080
54    3080
55    3080
27    3080
58    3080
Name: count, dtype: int64

Geolocation
-86.63186076199969 32.84057112200048      3080
-114.3637300419997 43.682630005000476     3080
-111.76381127699972 34.865970280000454    3080
-92.27449074299966 34.74865012400045      3080
-120.99999953799971 37.63864012300047     3080
-106.13361092099967 38.843840757000464    3080
-72.64984095199964 41.56266102000046      3080
-75.57774116799965 39.008830667000495     3080
-77.03196112699965 38.89037138500049      3080
-81.92896053899966 28.932040377000476     3080
-83.62758034599966 32.83968109300048      3080
-147.72205903599973 64.84507995700051     3080
-157.85774940299973 21.304850435000446    3080
-89.53803082499968 32.745510099000455     3080
-86.14996019399968 39.766910452000445     3080
-93.81649055599968 42.46940091300047      3080
-98.20078122699965 38.34774030000045      3080
-84.77497104799966 37.645970271000465     3080
-92.44568007099969 31.31266064400046      3080
-68.98503133599962 45.254228894000505     3080
-76.60926011099963 39.29058096400047      3080
-72.08269067499964 42.27687047000046      3080
-84.71439026999968 44.6613195430005       3080
-88.99771017799969 40.48501028300046      3080
-94.79420050299967 46.35564873600049      3080
-92.56630005299968 38.635790776000476     3080
-89.81637074199966 44.39319117400049      3080
-77.86070029399963 40.79373015200048      3080
-117.07184056399967 39.493240390000494    3080
-71.50036091999965 43.65595011300047      3080
-74.27369128799967 40.13057004800049      3080
-106.24058098499967 34.52088095200048     3080
-75.54397042699964 42.82700103200045      3080
-79.15925046299964 35.466220975000454     3080
-100.11842104899966 47.47531977900047     3080
-82.40426005599966 40.06021014100048      3080
-97.52107021399968 35.47203135600046      3080
-99.36572062299967 41.6410409880005       3080
-120.15503132599969 44.56744942400047     3080
-109.42442064499971 47.06652897200047     3080
-81.04537120699968 33.998821303000454     3080
-100.3735306369997 44.353130053000484     3080
-85.77449091399967 35.68094058000048      3080
-99.42677020599967 31.827240407000488     3080
-111.58713063499971 39.360700171000474    3080
-72.51764079099962 43.62538123900049      3080
-78.45789046299967 37.54268067400045      3080
-120.47001078999972 47.52227862900048     3080
-80.71264013499967 38.66551020200046      3080
-71.52247031399963 41.70828019300046      3080
-108.10983035299967 43.23554134300048     3080
Name: count, dtype: int64

Latitude
-86.63186076199969     3080
-114.3637300419997     3080
-111.76381127699972    3080
-92.27449074299966     3080
-120.99999953799971    3080
-106.13361092099967    3080
-72.64984095199964     3080
-75.57774116799965     3080
-77.03196112699965     3080
-81.92896053899966     3080
-83.62758034599966     3080
-92.56630005299968     3080
-157.85774940299973    3080
-89.53803082499968     3080
-86.14996019399968     3080
-93.81649055599968     3080
-98.20078122699965     3080
-84.77497104799966     3080
-92.44568007099969     3080
-68.98503133599962     3080
-76.60926011099963     3080
-72.08269067499964     3080
-84.71439026999968     3080
-88.99771017799969     3080
-109.42442064499971    3080
-99.36572062299967     3080
-108.10983035299967    3080
-147.72205903599973    3080
-117.07184056399967    3080
-71.50036091999965     3080
-74.27369128799967     3080
-106.24058098499967    3080
-75.54397042699964     3080
-79.15925046299964     3080
-100.11842104899966    3080
-82.40426005599966     3080
-97.52107021399968     3080
-120.15503132599969    3080
-77.86070029399963     3080
-71.52247031399963     3080
-81.04537120699968     3080
-100.3735306369997     3080
-85.77449091399967     3080
-99.42677020599967     3080
-111.58713063499971    3080
-72.51764079099962     3080
-78.45789046299967     3080
-120.47001078999972    3080
-80.71264013499967     3080
-89.81637074199966     3080
-94.79420050299967     3080
nan                    3080
Name: count, dtype: int64

Longitude
32.84057112200048     3080
43.682630005000476    3080
34.865970280000454    3080
34.74865012400045     3080
37.63864012300047     3080
38.843840757000464    3080
41.56266102000046     3080
39.008830667000495    3080
38.89037138500049     3080
28.932040377000476    3080
32.83968109300048     3080
38.635790776000476    3080
21.304850435000446    3080
32.745510099000455    3080
39.766910452000445    3080
42.46940091300047     3080
38.34774030000045     3080
37.645970271000465    3080
31.31266064400046     3080
45.254228894000505    3080
39.29058096400047     3080
42.27687047000046     3080
44.6613195430005      3080
40.48501028300046     3080
47.06652897200047     3080
41.6410409880005      3080
43.23554134300048     3080
64.84507995700051     3080
39.493240390000494    3080
43.65595011300047     3080
40.13057004800049     3080
34.52088095200048     3080
42.82700103200045     3080
35.466220975000454    3080
47.47531977900047     3080
40.06021014100048     3080
35.47203135600046     3080
44.56744942400047     3080
40.79373015200048     3080
41.70828019300046     3080
33.998821303000454    3080
44.353130053000484    3080
35.68094058000048     3080
31.827240407000488    3080
39.360700171000474    3080
43.62538123900049     3080
37.54268067400045     3080
47.52227862900048     3080
38.66551020200046     3080
44.39319117400049     3080
46.35564873600049     3080
nan                   3080
Name: count, dtype: int64

In [9]:
df.tail(4)

,RowId,YearStart,LocationAbbr,LocationDesc,DataSource,PriorityArea1,PriorityArea2,PriorityArea3,PriorityArea4,Class,Topic,Question,Data_Value_Type,Data_Value_Unit,Data_Value,Data_Value_Alt,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Break_Out_Category,Break_Out,ClassId,TopicId,QuestionId,Data_Value_TypeID,BreakOutCategoryId,BreakOutId,LocationId,Geolocation,Latitude,Longitude
160156,BRFSS~2020~58~BR012~RAC04~Age-Standardized,1970,USM,Median of all states,BRFSS,NaN,NaN,Healthy People 2030,NaN,Risk Factors,Hypertension,Prevalence of hypertension medication use amon...,Age-Standardized,Percent (%),NaN,-1.0,-,Data not available,NaN,NaN,Race,Hispanic,C2,T9,BR012,AgeStdz,BOC04,RAC04,58,NaN,nan,nan
160157,BRFSS~2020~58~BR012~RAC04~Crude,1970,USM,Median of all states,BRFSS,NaN,NaN,Healthy People 2030,NaN,Risk Factors,Hypertension,Prevalence of hypertension medication use amon...,Crude,Percent (%),NaN,-1.0,-,Data not available,NaN,NaN,Race,Hispanic,C2,T9,BR012,Crude,BOC04,RAC04,58,NaN,nan,nan
160158,BRFSS~2020~58~BR012~RAC07~Crude,1970,USM,Median of all states,BRFSS,NaN,NaN,Healthy People 2030,NaN,Risk Factors,Hypertension,Prevalence of hypertension medication use amon...,Crude,Percent (%),NaN,-1.0,-,Data not available,NaN,NaN,Race,Other,C2,T9,BR012,Crude,BOC04,RAC07,58,NaN,nan,nan
160159,BRFSS~2020~58~BR012~RAC07~Age-Standardized,1970,USM,Median of all states,BRFSS,NaN,NaN,Healthy People 2030,NaN,Risk Factors,Hypertension,Prevalence of hypertension medication use amon...,Age-Standardized,Percent (%),NaN,-1.0,-,Data not available,NaN,NaN,Race,Other,C2,T9,BR012,AgeStdz,BOC04,RAC07,58,NaN,nan,nan

In [10]:
# ## Data Break Down

# The rows are unique and data is wrapped into the row id:
#   Row ID Format: DataSource-Year-LocationID-QuestionId-BreakOutId-Data_Value_Type
#                  BRFSS~2011~01~BR001~OVR01~Age-Standardized	


# YearStart 

# ### Location Info:
#     LocationAbbr                
#     LocationDesc  
#     LocationId                  
#     Geolocation                   
#     Latitude                      
#     Longitude                                   

# ### Data Values:   
#     Data_Value_Unit               
#     Data_Value                    
#     Data_Value_Alt                
#     Data_Value_Footnote_Symbol    
#     Data_Value_Footnote         
#     Low_Confidence_Limit          
#     High_Confidence_Limit     
#     DataSource -- constant for all rows --
#     Data_Value_Type
#         Age-Standardized     58240
#         Crude               101920
#         Name: count, dtype: int64

# ### Priority Area:
# PriorityArea1              
#     Million Hearts    22880
# PriorityArea3 
#     Healthy People 2030    80080                 
# PriorityArea2  - all NaN          
# PriorityArea4   - all NaN          

# ## Break Downs

# Class
#     Cardiovascular Diseases     57200
#     Risk Factors               102960                         
# Topic   
#     Coronary Heart Disease                        11440
#     Diabetes                                      11440
#     Major Cardiovascular Disease                  11440
#     Nutrition                                     11440
#     Obesity                                       11440
#     Physical Inactivity                           11440
#     Smoking                                       11440
#     Stroke                                        11440
#     Acute Myocardial Infarction (Heart Attack)    22880
#     Cholesterol Abnormalities                     22880
#     Hypertension                                  22880               

# Question
#     Prevalence of acute myocardial infarction (heart attack) among US adults (18+); BRFSS                    11440                 
#     Prevalence of cholesterol screening in the past 5 years among US adults (20+); BRFSS                     11440                 
#     Prevalence of consuming fruits and vegetables less than 5 times per day among US adults (18+); BRFSS     11440                 
#     Prevalence of coronary heart disease among US adults (18+); BRFSS                                        11440                 
#     Prevalence of current smoking among US adults (18+); BRFSS                                               11440                 
#     Prevalence of diabetes among US adults (18+); BRFSS                                                      11440                 
#     Prevalence of high total cholesterol among US adults (20+); BRFSS                                        11440                 
#     Prevalence of hypertension among US adults (18+); BRFSS                                                  11440                 
#     Prevalence of hypertension medication use among US adults (18+) with hypertension; BRFSS                 11440                 
#     Prevalence of major cardiovascular disease among US adults (18+); BRFSS                                  11440                 
#     Prevalence of obesity among US adults (20+); BRFSS                                                       11440                 
#     Prevalence of physical inactivity among US adults (18+); BRFSS                                           11440                 
#     Prevalence of post-hospitalization rehabilitation among heart attack patients, US adults (18+); BRFSS    11440                 
#     Prevalence of stroke among US adults (18+); BRFSS                                                        11440                 

# Break_Out_Category
#     Overall    14560
#     Gender     29120
#     Age        43680
#     Race       72800

# Break_Out
#     20-24                  1560
#     18-24                  5720
#     25-44                  7280
#     35+                    7280
#     45-64                  7280
#     65+                    7280
#     75+                    7280
#     Female                14560
#     Hispanic              14560
#     Male                  14560
#     Non-Hispanic Asian    14560
#     Non-Hispanic Black    14560
#     Non-Hispanic White    14560
#     Other                 14560
#     Overall               14560                


# ### ID Columns:
# ClassId                     
# TopicId                     
# QuestionId                  
# Data_Value_TypeID           
# BreakOutCategoryId          
# BreakOutId